{% set name = "flask-bcrypt" %}
{% set camelName = "Flask-Bcrypt" %}
{% set bundle = "tar.gz" %}
{% set version = "1.0.1" %}
{% set hash_type = "sha256" %}
{% set hash_val = "f07b66b811417ea64eb188ae6455b0b708a793d966e1a80ceec4a23bc42a4369" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ bundle }}
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ camelName }}-{{ version }}.{{ bundle }}
  {{ hash_type }}: {{ hash_val }}

build:
  number: 0
  script: python -m pip install --no-deps --ignore-installed .
  skip: True  # [py<37 and py>38]

requirements:
  host:
    - python 3.8.13
    - pip
    - setuptools
    - wheel

  run:
    - python 3.8.13
    - flask
    - bcrypt >=3.1.1

test:
  imports:
    - flask_bcrypt
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/maxcountryman/flask-bcrypt
  license: BSD-3-Clause
  license_file: LICENSE
  license_family: BSD
  summary: Bcrypt hashing for Flask.
  description: Flask-Bcrypt is a Flask extension that provides bcrypt hashing utilities for your application.
  dev_url: https://github.com/maxcountryman/flask-bcrypt
  doc_url: https://flask-bcrypt.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - pmlandwehr
