{% set name = "flask-bcrypt" %}
{% set camelName = "Flask-Bcrypt" %}
{% set bundle = "tar.gz" %}
{% set version = "1.0.1" %}
{% set hash_type = "sha256" %}
{% set hash_val = "f07b66b811417ea64eb188ae6455b0b708a793d966e1a80ceec4a23bc42a4369" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ bundle }}
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ camelName }}-{{ version }}.{{ bundle }}
  {{ hash_type }}: {{ hash_val }}

build:
  number: 0
  script: python -m pip install --no-deps --ignore-installed .
  skip: True  # [py<37]

requirements:
  host:
    - python
    - pip

  run:
    - python
    - flask
    - bcrypt

test:
  imports:
    - flask_bcrypt

about:
  home: https://github.com/maxcountryman/flask-bcrypt
  license_file: LICENSE
  license_family: BSD
  license: BSD 3-Clause
  summary: 'Bcrypt hashing for Flask.'
  dev_url: https://github.com/maxcountryman/flask-bcrypt
  doc_url: https://flask-bcrypt.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - pmlandwehr
