# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: beta-xcode6.1

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=34
    - CONDA_PY=35
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "OebIZ/vFJKOvm7xp/1MnDI2XiyItGy4h0vGBKOgiTxTnu1ZjhLULqy+po+kBQIB/eyT3Nw2QRWmPuN4rLr1Rztut7AySHM5QzHBIM4/MPyAMQY06S3snSP507nfNkUFa2+7X4x/Zt23MDNtwXAUPMWTkQY70DhlLp7laxRrYg1lZBIKHaJRJrgkcZfrFhdsruqYQ6ctuUrhWzGQX85h6OfoL+3BAiAwe5NTdEE0b2pEAY9xnn/bYboLSCs8meD2X1Du2rrSEYYNUu2szgEythqVupY5+vSQOJKxXHcBuxZjiBjxHfRN1Oh5tpA7GLpl90nM57MXoUGpOrFfHox5adl6iRneIb/Q2KbGEZWEHOSMoXWsOJYg1Dfi46E58w35IF2VHYZFHZV3U1byzrTKlGlzfFtv1Gl0CDbKxAGENDeN/8j3br4vrRwxhMOh2H1IsGWodLrST+aS+fVK/+EF7uY2LsChLD1E5wrE8nYRhkKogmXMRcIPUf1SNiTmuqpyJVZZx+XbHrk41+FfmXpHpS57W03TzM+QL51i5a5ohX8ztffumZIUksWAETiOKU9AI6UFOGvQJCRe4KyiJrbWZ7O4vXGC3WlZO55bvUmAgx49VsLD02Rk1be8Q+SwaGKsbOOttFnYQU0b3w/KtT0KZ0ShHjtOEhAEGiqQ6EyNo6XY="


before_install:
    # Remove homebrew.
    - brew remove --force $(brew list)
    - brew cleanup -s
    - rm -rf $(brew --cache)

install:
    - |
      MINICONDA_URL="http://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

      source /Users/travis/miniconda3/bin/activate root
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
