travis:
  secure:
    BINSTAR_TOKEN: J8dUgJ5BZHXWFbqxzD27m3UxfD+qGMOhro1OJzBRZ69OOlMIKpIZEYue6CqpSsmg03203gOIY9GUFyzkT57hAb6Nx0qkKg6UyupTGsrGvnwK/MUqkw2Hp5UpBXEWeK9k56xIo2VJKyNRJx/8SshrIEeD2IbaRBAWI+6O4Vrwd1/tIAc0277N75HkqM38SS9z9hokv+OKf9zZcD1KCoX0bYa5WLHl3qgAVCpuB+GReAbdZNDLcIHB0H8wtQ9PDHfd4xxNuD2jdD6KKdYyY59H5UbkMduqZCybc2Jm+CGoS6DrVBYgtHlO3xJ70iw2UQuIZCTlyCgKtMcHLCTJbEKoo0zkzIG7c9wunYbUCnLjaDvQ3WeFHaqYUdu75RuLxsWYrp1NvrGYUmelqxby3iHLucKZO8N0x7Bpi2v6JJCI5GJCpkVf/4co1YyYuBtbiwi/hYkZR8NRHA88GhCKJ9l93zjSgfy+SYzHLc/IcJkSuKkDGYUoAgTWWcHvYVq24N5uRqX1rXuc/xf4gkRiFCEaxRES3g/JDaUk0l/mLRPxAQnx71vgnGcK2oW6MBfybJmHV6xPJEAR9d7brY8Cv4W23cVpvBm/iG7VlJOMgKRd5SKU4/L2aCpSzOhb6kcnVlXVwVeRjWbwFO+cre1XdkdijnFAdUQzUbl6j0c5oASPipc=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
