travis:
  secure:
    BINSTAR_TOKEN: OebIZ/vFJKOvm7xp/1MnDI2XiyItGy4h0vGBKOgiTxTnu1ZjhLULqy+po+kBQIB/eyT3Nw2QRWmPuN4rLr1Rztut7AySHM5QzHBIM4/MPyAMQY06S3snSP507nfNkUFa2+7X4x/Zt23MDNtwXAUPMWTkQY70DhlLp7laxRrYg1lZBIKHaJRJrgkcZfrFhdsruqYQ6ctuUrhWzGQX85h6OfoL+3BAiAwe5NTdEE0b2pEAY9xnn/bYboLSCs8meD2X1Du2rrSEYYNUu2szgEythqVupY5+vSQOJKxXHcBuxZjiBjxHfRN1Oh5tpA7GLpl90nM57MXoUGpOrFfHox5adl6iRneIb/Q2KbGEZWEHOSMoXWsOJYg1Dfi46E58w35IF2VHYZFHZV3U1byzrTKlGlzfFtv1Gl0CDbKxAGENDeN/8j3br4vrRwxhMOh2H1IsGWodLrST+aS+fVK/+EF7uY2LsChLD1E5wrE8nYRhkKogmXMRcIPUf1SNiTmuqpyJVZZx+XbHrk41+FfmXpHpS57W03TzM+QL51i5a5ohX8ztffumZIUksWAETiOKU9AI6UFOGvQJCRe4KyiJrbWZ7O4vXGC3WlZO55bvUmAgx49VsLD02Rk1be8Q+SwaGKsbOOttFnYQU0b3w/KtT0KZ0ShHjtOEhAEGiqQ6EyNo6XY=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
