travis:
  secure:
    BINSTAR_TOKEN: MwTBI27l2ey0I3+eToh+SOrDXfdOUqBHP8GzzJQh2hL3Ptza6niBMYtnsjo4zaMLzYuDgNFUGpdsW2gm5eaWOHh80EN7SnYon5jF5kdlioHPtaltCmsvGuYGt2sDtVQrQaKbsBbELx/p4O/jwB9xC5NuaAGgXc2JDfwcf/JAAoHbqUXt1SMJjySzd30HvN7+VTVuBGbCqEm/dgKZif0vZ5HIQdLcy3NKMsK6rUicFCXvA+uGSyNkBUgIuLyhQMCy0KdiXpIoVemwzwRuhVI6oZVrkFaCDpEn/tSwS/QX+X+HJVJ7o7XXztWn9Lm6Bqfq50E1MWd4YTYotxe4WN9AWjmGuuRMfVNEQo2FiOC/GtbyhwE8X1SF01A4Lv2dlCbHaorLhsTmc44W/k7Q7sQw/8ZB0uDS0LTQOQk682CcQ3kp2kmxl/6pAXMLPMX/JNDDHZnpWp7Smaf9HIT/Wll5IsVTt7ZDAUB/vk0eSjlCMrm3BOaBufz+FN0aFJTr3pSxm8gPTIpa0bZ+wD1fN34uxBRsRuDVRnLzUhHEzAqaAkwPETAknpkd6ZQ+6HBJwhDrX/PSm3DEO3SgpYNHhb/tb4ke3Ok8UHRyq45j7rEm4VsXDDMFPS5jErxamGchqYZurOrkK8xXBO+mYZ2mGrBsJwmbag1hlfAkzICD9wpViLs=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
